# Generated by Django 4.2.28 on 2026-02-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='external_links',
            field=models.JSONField(blank=True, default=list, help_text='List of dicts with title and url'),
        ),
        migrations.AddField(
            model_name='blogentry',
            name='github_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
