# Generated by Django 4.2.28 on 2026-02-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogentry_external_links_blogentry_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
    ]
