# Generated by Django 4.2.28 on 2026-02-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogentry_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='learning_materials_html',
            field=models.TextField(blank=True, help_text='HTML content for learning materials', null=True),
        ),
    ]
